# https://dart.dev/guides/language/analysis-options

include: package:pedantic/analysis_options.yaml
#include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - 'example/**'
    - 'build/**'
    - 'lib/*.g.dart'
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: info
    unsafe_html: warning

# https://dart-lang.github.io/linter/lints/
linter:
  rules:
    #false
    public_member_api_docs: false
    avoid_types_on_closure_parameters: false
    omit_local_variable_types: false

    # true
    unnecessary_const: true
    avoid_shadowing_type_parameters: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    avoid_relative_lib_imports: true
    avoid_print: true
    unsafe_html: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    prefer_void_to_null: true
    avoid_empty_else: true
    unnecessary_new: true
    unnecessary_this: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    await_only_futures: true
    avoid_void_async: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    non_constant_identifier_names: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_statements: true
    directives_ordering: true