include: package:pedantic/analysis_options.yaml
#include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - 'example/**'
    - 'build/**'
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
    

linter:
  rules:
    unnecessary_new: false
    unnecessary_this: false
    public_member_api_docs: false
    avoid_shadowing_type_parameters: false
    avoid_types_on_closure_parameters: false
    omit_local_variable_types: false
    await_only_futures: true
    avoid_void_async: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    non_constant_identifier_names: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_statements: true
    directives_ordering: true