name: awesome1c
description: 1C:Awesome
version: 0.0.1+1
author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/plugfox

environment:
  sdk: ">=2.7.9 <3.0.0"
  flutter: ">=1.15.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.4
  #firebase_core: ^0.4.4
  #firebase_auth: ^0.15.4
  #cloud_firestore: ^0.13.3
  provider: ^4.0.4
  bloc: ^3.0.0
  dio: ^3.0.8
  retrofit: ^1.3.0
  hive: ^1.3.0
  rxdart: ^0.23.1
  json_annotation: ^3.0.0
  google_fonts: ^0.3.9
  url_launcher: ^5.4.1

dev_dependencies:
  pedantic: any
  effective_dart: any
  json_serializable: any
  hive_generator: any
  retrofit_generator: any
  build_runner: any
  build_test: any
  test: any
  flutter_test:
    sdk: flutter

dependency_overrides:

flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700  
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages