name: awesome1c
description: 1C:Awesome
version: 0.1.0+3
author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/plugfox

environment:
  sdk: ">=2.7.9 <3.0.0"
  flutter: ">=1.15.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4
  google_sign_in: ^4.1.4
  provider: ^4.1.0-dev
  bloc: ^3.0.0
  dio: ^3.0.9
  retrofit: ^1.3.1+1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  rxdart: ^0.23.1
  json_annotation: ^3.0.1
  #uuid: ^2.0.4
  #animations: ^1.0.0+5
  #google_fonts: ^0.3.9
  #url_launcher: ^5.4.1
  #freezed_annotation: ^0.7.0
  #auto_size_text 2.1.0
  #qr_flutter 3.2.0
  #shimmer 1.0.1
  #mime 0.9.6+3
  #percent_indicator 2.1.1+1
  #date_format 1.0.8
  #timeago 2.0.26
  #rflutter_alert 1.0.3
  #badges 1.1.1
  #timeago 2.0.26
  #animated_text_kit 2.0.0
  #flutter_spinkit 4.1.2
  #intro_slider 2.2.9
  #introduction_screen 1.0.8
  #flare_flutter 2.0.1
  #feature_discovery 0.8.0
  #showcaseview 0.1.5
  #tutorial_coach_mark 0.3.0
  #archive 2.0.13
  #path 1.6.4
  #crypto 2.1.4
  #encrypt 4.0.0
  #args 1.5.3
  #xml 3.7.0


dev_dependencies:
  pedantic: any
  effective_dart: any
  json_serializable: any
  #freezed: any
  hive_generator: any
  retrofit_generator: any
  build_runner: any
  build_test: any
  test: any
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icons/iconxxxhdpi.png"
  image_path_android: "assets/icons/iconxxxhdpi.png"
  image_path_ios: "assets/icons/iconxxxhdpi.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/icons/background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/icons/foreground.png" # only available for Android 8.0 devices and above

dependency_overrides:

flutter:
  uses-material-design: true

  assets:
    - assets/images/unauthorized_user.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/ttf/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/ttf/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/ttf/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/ttf/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons/ttf/MaterialIcons-Regular.ttf
